### ISSUE TITLE
unable to run async tests in UWP

### ISSUE THREAD

**Issue by tofutim** [nunit/nunit.xamarin#35] opened 2015-11-18 16:17 UTC
Is this a UWP, nunit, nunit.runners issue? I added this to the tests in this solution after seeing it in mine. This is a result from the UWP emulator (Windows 10 mobile) in VS2015 on Server 2012 R2.

        [Test]
        public async Task AsyncTest()
        {
            var result = await anInt();
            Assert.AreEqual(42, result);
        }

        private async Task<int> anInt()
        {
            return 42;
        }

![image](https://cloud.githubusercontent.com/assets/157766/11246511/cef21880-8dcc-11e5-88cf-613c49124dc2.png)

**Comment by tofutim** [comment] 2015-11-18 18:21
Sadly go.microsoft.com/fwlink/?LinkId=248273 goes just to an msdn main page. :(

**Comment by rprouse** [comment] 2015-11-18 18:59
I have confirmed that this is an issue with the portable version of the NUnit framework. I am going to move this bug there.

**Comment by tofutim** [comment] 2015-11-18 19:02
Thanks!

**Comment by rprouse** [comment] 2015-11-18 19:07
I am closing this here since it is a framework bug. It is now being tracked as nunit/nunit#1037

**Closed by rprouse** 2015-11-18 19:07 UTC

**Comment by rprouse** [comment] 2015-12-03 23:51
@tofutim just to let you know, 3.0.1 has been released and it fixes this bug.

**Comment by tofutim** [comment] 2015-12-04 00:20
Yay!
